### ISSUE TITLE
1993-09-05 敬老の日

### ISSUE THREAD

**Issue by osamutake** [hitsujiwool/node-holiday-jp#1]
1993年の敬老の日は9/5ではなく9/15ですね。
ミスタイプでしょうか？

**Comment by osamutake** [comment]
2019-08-12 振替休日
2024-08-12 振替休日
2030-08-12 振替休日
2041-08-12 振替休日
2047-08-12 振替休日

も、本家では直っているようでした。
https://github.com/komagata/holiday_jp/blame/master/holidays.yml

**Comment by hitsujiwool** [comment]
ご指摘ありがとうございます。本家（Ruby版）に追従したバージョンをリリースしました。
